FROM adoptopenjdk/openjdk11-openj9:jdk-11.0.8_10_openj9-0.21.0-alpine-slim

RUN apk update && apk add unzip

RUN mkdir -p /home/app
WORKDIR /home/app

COPY historian/build/distributions/historian-0.1.0.zip .

RUN unzip historian-0.1.0.zip -d .
RUN rm historian-0.1.0.zip

ENTRYPOINT ["sh", "historian-0.1.0/bin/historian"]
