/*
 * generated by Xtext 2.18.0.M1
 */
package com.rigiresearch.middleware.hcl.interpreter.parser.antlr;

import com.google.inject.Inject;
import com.rigiresearch.middleware.hcl.interpreter.parser.antlr.internal.InternalHclParser;
import com.rigiresearch.middleware.hcl.interpreter.services.HclGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class HclParser extends AbstractAntlrParser {

	@Inject
	private HclGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalHclParser createParser(XtextTokenStream stream) {
		return new InternalHclParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public HclGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(HclGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
