<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="monitoring" nsURI="http://www.rigiresearch.com/middleware/Monitoring"
    nsPrefix="monitoring">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="bundleManifest" value="false"/>
    <details key="modelDirectory" value="model/build/xcore/main"/>
    <details key="complianceLevel" value="8.0"/>
    <details key="basePackage" value="com.rigiresearch.middleware.metamodels"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EDataType" name="URI" instanceClassName="java.net.URI"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Function" instanceClassName="java.util.function.Function">
    <eTypeParameters name="A"/>
    <eTypeParameters name="R"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Monitor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;p>A polling monitor associated with a specific data model and an endpoint&#xA;that returns the instances of the data model."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="path" eType="#//Path" containment="true"
        resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="schema" eType="#//Schema"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rate" eType="#//CronExpression"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="equivalences" upperBound="-1"
        eType="#//Equivalence" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Path">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;p>A GET HTTP path."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" unique="false" eType="#//URI"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Property" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Schema">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;p>An API response class."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Property" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;p>A schema property."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" unique="false" eType="#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="required" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Equivalence">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;p>A pair of source-target properties that represents a relationship between&#xA;an property from the API specification model and the environment model.&#xA;&lt;p>The {@code transform} function processes the properties as needed. It&#xA;should be the identity function if no transformation is needed."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//ContainedProperty"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//ContainedProperty"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transform" unique="false">
      <eGenericType eClassifier="#//Function">
        <eTypeArguments eClassifier="#//ContainedProperty"/>
        <eTypeArguments eClassifier="#//ContainedProperty"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainedProperty">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;p>A property contained either by the source or target model."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" eType="#//Property"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="container" unique="false"
        eType="#//PropertyContainer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CronExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;p>A Unix-like cron expression."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Type">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Possible property types based on the OpenAPI specificatin"/>
    </eAnnotations>
    <eLiterals name="ARRAY"/>
    <eLiterals name="BOOLEAN"/>
    <eLiterals name="INTEGER"/>
    <eLiterals name="NUMBER"/>
    <eLiterals name="OBJECT"/>
    <eLiterals name="STRING"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PropertyContainer">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;p>The source container for a given property."/>
    </eAnnotations>
    <eLiterals name="MODEL"/>
    <eLiterals name="API"/>
  </eClassifiers>
</ecore:EPackage>
