version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-cache-{{ .Branch }}-{{ checksum "build.gradle" }}
      - run:
          name: Install gradle dependencies
          command: ./gradlew dependencies
      - save_cache:
          key: gradle-cache-{{ .Branch }}-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle
      - run:
          name: Run tests
          command: ./gradlew check
