/**
 * generated by Xtext 2.18.0.M1
 */
package com.rigiresearch.middleware.hcl.interpreter;

import com.rigiresearch.middleware.hcl.interpreter.AbstractHclRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class HclRuntimeModule extends AbstractHclRuntimeModule {
}
