/**
 * generated by Xtext 2.18.0.M1
 */
package com.rigiresearch.middleware.hcl.interpreter;

import com.google.inject.Injector;
import com.rigiresearch.middleware.hcl.interpreter.HclStandaloneSetupGenerated;
import com.rigiresearch.middleware.hcl.model.ModelPackage;
import org.eclipse.emf.ecore.EPackage;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class HclStandaloneSetup extends HclStandaloneSetupGenerated {
  public static void doSetup() {
    new HclStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
  
  @Override
  public void register(final Injector injector) {
    boolean _containsKey = EPackage.Registry.INSTANCE.containsKey(ModelPackage.eNS_URI);
    boolean _not = (!_containsKey);
    if (_not) {
      EPackage.Registry.INSTANCE.put(ModelPackage.eNS_URI, ModelPackage.eINSTANCE);
    }
    super.register(injector);
  }
}
