# 1. client* <--> (proxy-cache* <--> front-end) <--> back-end*
# 2. client* <--> proxy-cache <--> front-end* <--> back-end*
# 3. client* <--> LB* (Ingress) <--> (sharded) proxy-cache* <--> front-end* <--> back-end*
# 3.1 Shared cache through file system--Not needed because cache is being sharded
# 3.2 Independent cache storage

apiVersion: v1
kind: ConfigMap
metadata:
  name: cache-layer-configmap
data:
  # Read more at https://www.nginx.com/blog/nginx-caching-guide/
  nginx.conf: |
    proxy_cache_path /cache-data levels=1:2 keys_zone=my_cache:10m max_size=10g
                     inactive=60m use_temp_path=off;

    log_format rt_cache '$upstream_cache_status [$server_addr]  '
                        '"$request_uri" $status $body_bytes_sent ';

    upstream my_server {
        server youtube-dl-frontend:8080;
    }

    server {
        listen 80;
        server_name localhost;
        access_log   /var/log/nginx/access.log rt_cache;

        location / {
            proxy_hide_header Cache-Control;
            proxy_ignore_headers Cache-Control;
            proxy_cache_valid any 48h;

            proxy_cache my_cache;
            proxy_cache_key $request_uri;
            proxy_cache_revalidate off;
            proxy_cache_min_uses 0;
            proxy_cache_use_stale error timeout updating http_500 http_502
                                  http_503 http_504;
            proxy_cache_background_update on;
            proxy_cache_lock on;
            proxy_cache_lock_age 30s;
            proxy_cache_lock_timeout 60s;
            proxy_send_timeout 300s;
            proxy_read_timeout 300s;
            proxy_connect_timeout 75s;

            proxy_pass http://my_server;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            add_header X-Cached $upstream_cache_status;
        }
    }
---
# Storage stuff for oracle cloud is explained here:
# https://blogs.oracle.com/cloud-infrastructure/post/using-file-storage-service-with-container-engine-for-kubernetes
# Doing that is necessary to use ReadWriteMany
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: oci-fss
provisioner: oracle.com/oci-fss
parameters:
  # Insert mount target from the FSS here
  mntTargetId: #mount_target_ocid#
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: oke-fsspv
spec:
  storageClassName: oci-fss
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nosuid
  nfs:
    # Replace this with the IP of your FSS file system in OCI
    server: 10.0.3.10
    # Replace this with the Path of your FSS file system in OCI
    path: "/sharedfs"
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oke-fsspvc
spec:
  storageClassName: oci-fss
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      # Although storage is provided here it is not used for FSS file systems
      storage: 2Gi
  volumeName: oke-fsspv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-dl-backend
spec:
  replicas: 5
  selector:
    matchLabels:
      app: youtube-dl
      tier: backend
  template:
    metadata:
      labels:
        app: youtube-dl
        tier: backend
    spec:
      containers:
        - image: jachinte/youtube-dl-grpc
          name: youtube-dl-grpc
          ports:
            - containerPort: 50051
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:50051"]
            initialDelaySeconds: 5
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:50051"]
            initialDelaySeconds: 10
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 32Mi
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: youtube-dl-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: youtube-dl-backend
  minReplicas: 5
  maxReplicas: 100
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageValue: 64Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-dl-frontend
spec:
  replicas: 5
  selector:
    matchLabels:
      app: youtube-dl
      tier: frontend
  template:
    metadata:
      labels:
        app: youtube-dl
        tier: frontend
    spec:
      containers:
        - image: jachinte/youtube-dl-rest
          name: youtube-dl-rest
          ports:
            - containerPort: 8080
          env:
            - name: ENCODING_HOST
              value: youtube-dl-backend
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 32Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-dl-cache
spec:
  replicas: 5
  selector:
    matchLabels:
      app: youtube-dl
      tier: cache
  template:
    metadata:
      labels:
        app: youtube-dl
        tier: cache
    spec:
      containers:
        - image: nginx
          name: proxy-cache
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 32Mi
          volumeMounts:
            - name: cache-config-volume
              mountPath: /etc/nginx/conf.d
            - name: cache-volume
              mountPath: "/cache-data"
      volumes:
        - name: cache-config-volume
          configMap:
            name: cache-layer-configmap
        - name: cache-volume
          persistentVolumeClaim:
            claimName: oke-fsspvc
            readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: youtube-dl-backend
spec:
  selector:
    app: youtube-dl
    tier: backend
  ports:
    - port: 50051
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: youtube-dl-frontend
spec:
  selector:
    app: youtube-dl
    tier: frontend
  ports:
    - port: 8080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: youtube-dl-cache
spec:
  selector:
    app: youtube-dl
    tier: cache
  ports:
    - port: 80
      protocol: TCP
