/**
 * generated by Xtext 2.18.0.M1
 */
package com.rigiresearch.middleware.hcl.interpreter.scoping;

import com.rigiresearch.middleware.hcl.interpreter.scoping.AbstractHclScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class HclScopeProvider extends AbstractHclScopeProvider {
}
