/**
 * generated by Xtext 2.18.0.M1
 */
package com.rigiresearch.middleware.hcl.interpreter.validation;

import com.rigiresearch.middleware.hcl.interpreter.validation.AbstractHclValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class HclValidator extends AbstractHclValidator {
}
